name: Reusable docs build

on:
  workflow_call:
    inputs:
      docs-path:
        required: false
        type: string
        default: 'docs'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ inputs.docs-path }}/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          if [ -f ${{ inputs.docs-path }}/requirements.txt ]; then
            pip install -r ${{ inputs.docs-path }}/requirements.txt
          else
            pip install sphinx sphinx_rtd_theme myst_parser
          fi
      - name: Build docs
        run: |
          sphinx-build -b html ${{ inputs.docs-path }} _build/html
      - name: Upload HTML artifact for PRs
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: _build/html
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
